on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecsrende-wVtTCLjhID2l:53b87a37-456a-4ec1-9213-ec5e0a27a9d1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Render Amazon ECS task definition
      id: render-task-definition
      uses: aws-actions/amazon-ecs-render-task-definition@9ba9b39e2eb1b5d53ee0f7a78b7b5352b61b37e8
      with:
        task-definition: task-definition.json
        container-name: sample-app
        image: amazon/amazon-ecs-sample:latest

    - name: Validate Amazon ECS task definition
      env:
        TASK_DEF_FILE: ${{ steps.render-task-definition.outputs.task-definition }}
      run: |
        diff expected-task-definition.json $TASK_DEF_FILE

    - name: Register Amazon ECS task definition
      env:
        TASK_DEF_FILE: ${{ steps.render-task-definition.outputs.task-definition }}
      run: |
        aws ecs register-task-definition --cli-input-json file://$TASK_DEF_FILE
